version: "3"
services:
  nginx:
    image: nginx
    container_name: spotify_nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  api:
    container_name: spotify_api
    build:
      dockerfile: dev.backend.Dockerfile
      context: .
    env_file:
      - .env
    environment:
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"

  frontend:
    container_name: spotify_frontend
    build:
      dockerfile: dev.frontend.Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./vite.config.js:/app/vite.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./public:/app/public
      - ./index.html:/app/index.html
    environment:
      - VITE_API_LINK=http://localhost/api
    command: "npm start"