version: "3"
services:
  nginx:
    image: nginx
    container_name: spotify_nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  api:
    container_name: spotify_api
    build:
      dockerfile: dev.Dockerfile
      context: server
    env_file:
      - .env
    environment:
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./server:/app
    command: uvicorn main:app --host 0.0.0.0 --root-path /api
    ports:
      - "8000:8000"

  frontend:
    container_name: spotify_frontend
    build:
      dockerfile: dev.Dockerfile
      context: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/vite.config.js:/app/vite.config.js
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
    environment:
      - VITE_API_LINK=http://localhost/api
    command: "npm start"

  bpm:
    container_name: spotify_bpm
    build:
      dockerfile: Dockerfile
      context: bpm
    restart: unless-stopped
    ports:
      - "4000:4000"

  db:
    container_name: spotify_db
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: