version: "3"
services:
  nginx:
    image: nginx
    container_name: spotify_nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  frontend:
    container_name: spotify_frontend
    build:
      dockerfile: dev.Dockerfile
      context: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/vite.config.js:/app/vite.config.js
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
    command: "npm start"

  api:
    container_name: spotify_api
    build:
      dockerfile: dev.Dockerfile
      context: server
    restart: unless-stopped
    volumes:
      - ./server:/app
    env_file:
      - .env
    command: nodemon -L index.ts
    ports:
      - "4000:4000"

  db:
    container_name: spotify_db
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: