"""initial

Revision ID: 59f6c222767e
Revises: 
Create Date: 2023-12-24 17:36:12.479970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f6c222767e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    op.create_table('spotify_song_bpm',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spotify_song_bpm_id'), 'spotify_song_bpm', ['id'], unique=False)
    op.create_table('spotify_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spotify_token_id'), 'spotify_token', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spotify_token_id'), table_name='spotify_token')
    op.drop_table('spotify_token')
    op.drop_index(op.f('ix_spotify_song_bpm_id'), table_name='spotify_song_bpm')
    op.drop_table('spotify_song_bpm')
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_table('songs')
    # ### end Alembic commands ###
