name: Build backend image

on:
  push:
    branches: [ "master" ]
    paths:
      - 'server/**'
      - 'requirements.txt'
      - 'prod.backend.Dockerfile'
      - '.github/workflows/backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: prod.backend.Dockerfile
          tags: ghcr.io/matuszelenak/rich-spotify-playlist-api:latest
