name: Build backend image

on:
  push:
    branches: [ "github-actions" ]
    paths:
      - 'server/**'
      - 'requirements.txt'
      - 'backend.Dockerfile'
      - '.github/workflows/backend.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rich-spotify-playlist-api

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          push: true
          context: .
          file: backend.Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
